import fs from'node:fs';

const path='assets/js/app.js';
let app=fs.readFileSync(path,'utf8');
const required=(from,to,label)=>{
  if(!app.includes(from))throw new Error(`Source consolidation could not find: ${label}`);
  app=app.replace(from,to);
};

required("import{CHAT_PROMPTS,COUNTRY_FALLBACK,countryFromStorage,money}from'./app-config.js';","import{CHAT_PROMPT_SETS,COUNTRY_FALLBACK,countryFromStorage,money}from'./app-config.js';",'chat prompt import');
required("const RELEASE='20260731-production-certification-r1';","const RELEASE='20260801-source-consolidated-r1';",'release identifier');
required("const serverTime=value=>{const n=Date.parse(value||'');return Number.isFinite(n)?n:Date.now()};","const serverTime=value=>{const n=Date.parse(value||'');return Number.isFinite(n)?n:Date.now()};\nconst CHAT_SECONDS=45,CHAT_RECOVERY_MS=6*60*60*1000;\nconst chatRecoveryKey=()=>`earnchat-chat-recovery:${app.user?.id||'guest'}`;\nconst chatPrompts=()=>CHAT_PROMPT_SETS[Number(app.chat?.promptSet||0)]||CHAT_PROMPT_SETS[0];\nconst choosePromptSet=seed=>{let hash=0;for(const c of String(seed||Date.now()))hash=(hash*31+c.charCodeAt(0))>>>0;let index=hash%CHAT_PROMPT_SETS.length;const last=Number(localStorage.getItem('earnchat-last-prompt-set'));if(Number.isInteger(last)&&index===last)index=(index+1)%CHAT_PROMPT_SETS.length;localStorage.setItem('earnchat-last-prompt-set',String(index));return index};",'chat constants');
required("async function loadPublicLanding(){try{const stats=await api.publicStats();if(stats&&Number(stats.total_users)>0){$('#public-stats').classList.remove('hidden');$('#public-total').textContent=Number(stats.total_users).toLocaleString();$('#public-online').textContent=Number(stats.online_now||0).toLocaleString()}else $('#public-stats').classList.add('hidden')}catch{$('#public-stats').classList.add('hidden')}let payments=[],feedback=[];","async function loadPublicLanding(){let payments=[],feedback=[];",'public counter removal');
required("`About 2 minutes · ${reward} after approval`","`About 45 seconds · ${reward} after approval`",'home timing copy');
required("${today} of ${limit} approved · four replies · minimum two minutes","${today} of ${limit} approved · four replies · minimum 45 seconds",'earn timing copy');
required("function persistChat(){if(!app.chat)return sessionStorage.removeItem('earnchat-chat-recovery');sessionStorage.setItem('earnchat-chat-recovery',JSON.stringify({attemptId:app.chat.attemptId,partner:app.chat.partner,startedAt:app.chat.startedAt,stage:app.chat.stage,replies:app.chat.replies,replyTexts:app.chat.replyTexts}))}","function persistChat(){const key=chatRecoveryKey();if(!app.chat)return localStorage.removeItem(key);localStorage.setItem(key,JSON.stringify({attemptId:app.chat.attemptId,partner:app.chat.partner,startedAt:app.chat.startedAt,stage:app.chat.stage,replies:app.chat.replies,replyTexts:app.chat.replyTexts,promptSet:app.chat.promptSet,savedAt:Date.now(),expiresAt:Date.now()+CHAT_RECOVERY_MS}))}",'persistent chat recovery');
required("function clearChat(){clearInterval(app.chatTimer);app.chat=null;sessionStorage.removeItem('earnchat-chat-recovery')}","function clearChat(){clearInterval(app.chatTimer);app.chatTimer=null;app.chat=null;localStorage.removeItem(chatRecoveryKey())}",'clear persistent chat');
required("try{saved=JSON.parse(sessionStorage.getItem('earnchat-chat-recovery')||'null')}catch{}","try{saved=JSON.parse(localStorage.getItem(chatRecoveryKey())||'null');if(saved?.expiresAt&&Date.now()>Number(saved.expiresAt)){localStorage.removeItem(chatRecoveryKey());saved=null}}catch{localStorage.removeItem(chatRecoveryKey())}",'restore persistent chat');
required("app.chat={partner:meta.name,meta,attemptId:open.attempt_id,startedAt:serverTime(open.started_at),stage:same?Number(saved.stage||0):0,replies:same&&Array.isArray(saved.replies)?saved.replies:[],replyTexts:same&&Array.isArray(saved.replyTexts)?saved.replyTexts:[]};","app.chat={partner:meta.name,meta,attemptId:open.attempt_id,startedAt:serverTime(open.started_at),stage:same?Number(saved.stage||0):0,replies:same&&Array.isArray(saved.replies)?saved.replies:[],replyTexts:same&&Array.isArray(saved.replyTexts)?saved.replyTexts:[],promptSet:same&&Number.isInteger(Number(saved.promptSet))?Number(saved.promptSet):choosePromptSet(open.attempt_id)};",'resume prompt set');
required("function updateChatTimer(){if(!app.chat)return;const elapsed=Math.max(0,Math.floor((Date.now()-app.chat.startedAt)/1000)),remaining=Math.max(0,120-elapsed),fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;$('#chat-timer').textContent=`${fmt(elapsed)} / 02:00`;if(app.chat.replies.length===4){$('#chat-ready').classList.remove('hidden');$('#chat-complete').disabled=remaining>0;$('#chat-complete').textContent=remaining>0?`Ready in ${remaining}s`:'Complete guided session'}}","function updateChatTimer(){if(!app.chat)return;const elapsed=Math.max(0,Math.floor((Date.now()-app.chat.startedAt)/1000)),remaining=Math.max(0,CHAT_SECONDS-elapsed),fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;const timer=$('#chat-timer'),complete=$('#chat-complete');if(timer)timer.textContent=`${fmt(Math.min(elapsed,CHAT_SECONDS))} / 00:45`;if(app.chat.replies.length===4){$('#chat-ready')?.classList.remove('hidden');if(complete){complete.disabled=remaining>0;complete.textContent=remaining>0?`Ready in ${remaining}s`:'Complete guided session'}}}",'45-second timer');
required("app.chat={partner,meta,attemptId:attempt.attempt_id,startedAt:serverTime(attempt.started_at),stage:0,replies:[],replyTexts:[]};","app.chat={partner,meta,attemptId:attempt.attempt_id,startedAt:serverTime(attempt.started_at),stage:0,replies:[],replyTexts:[],promptSet:choosePromptSet(attempt.attempt_id)};",'new chat prompt set');
required("function openChatUi(message=''){$('#chat-title').textContent=app.chat.meta.name;$('#chat-subtitle').textContent=`${app.chat.meta.place} · ${app.chat.meta.topic}`;$('#chat-avatar').textContent=app.chat.meta.short;$('#chat-messages').innerHTML='';$('#chat-input').value='';$('#chat-input').disabled=false;$('#chat-send').disabled=false;$('#chat-ready').classList.add('hidden');clearMessage('#chat-message');addChatMessage('them',message||`Hi, I’m ${app.chat.meta.name.split(' ')[0]}. ${CHAT_PROMPTS[Math.min(app.chat.stage,3)].prompt}`);app.chat.replyTexts.forEach(text=>addChatMessage('me',text));renderChatStage();clearInterval(app.chatTimer);app.chatTimer=setInterval(updateChatTimer,1000);updateChatTimer();navigate('chat')}","function openChatUi(message=''){const set=chatPrompts();$('#chat-title').textContent=app.chat.meta.name;$('#chat-subtitle').textContent=`${app.chat.meta.place} · ${app.chat.meta.topic}`;$('#chat-avatar').textContent=app.chat.meta.short;$('#chat-messages').innerHTML='';$('#chat-input').value='';$('#chat-input').disabled=app.chat.replies.length>=4;$('#chat-send').disabled=app.chat.replies.length>=4;$('#chat-ready').classList.add('hidden');clearMessage('#chat-message');if(message)showMessage('#chat-message',message,'ok');addChatMessage('them',`Hi, I’m ${app.chat.meta.name.split(' ')[0]}. ${set[0].prompt}`);app.chat.replyTexts.forEach((text,index)=>{addChatMessage('me',text);if(index+1<app.chat.replyTexts.length||app.chat.replyTexts.length<4)addChatMessage('them',set[Math.min(index+1,set.length-1)].prompt)});if(app.chat.replyTexts.length===4)addChatMessage('them','Thanks for sharing. Your four guided replies are complete. You can finish when the 45-second timer is ready.');renderChatStage();clearInterval(app.chatTimer);app.chatTimer=setInterval(updateChatTimer,1000);updateChatTimer();navigate('chat')}",'restore full conversation');
required("const stage=Math.min(app.chat.stage,CHAT_PROMPTS.length-1),p=CHAT_PROMPTS[stage];","const set=chatPrompts(),stage=Math.min(app.chat.stage,set.length-1),p=set[stage];",'active prompt stage');
required("addChatMessage('them',CHAT_PROMPTS[app.chat.stage].prompt);","addChatMessage('them',chatPrompts()[app.chat.stage].prompt);",'next rotating prompt');
required("addChatMessage('them','Thanks for sharing. Your four guided replies are complete. Stay here until the two-minute session is ready to finish.');","addChatMessage('them','Thanks for sharing. Your four guided replies are complete. You can finish when the 45-second timer is ready.');",'final chat message');
required("if(Math.floor((Date.now()-app.chat.startedAt)/1000)<120)return;","if(Math.floor((Date.now()-app.chat.startedAt)/1000)<CHAT_SECONDS)return;",'completion threshold');
required("sessionStorage.removeItem('earnchat-chat-recovery');","localStorage.removeItem(chatRecoveryKey());",'completion recovery cleanup');
required("$('#chat-ready').innerHTML=`<b>Guided chat completed</b><small>${credited?`${format(credited)} approved · `:''}${remaining} chat${remaining===1?'':'s'} remaining today.</small><div class=\"wallet-tabs\"><button class=\"secondary\" id=\"chat-return\">Return to Earn</button><button class=\"primary\" id=\"chat-another\">${remaining?'Start another chat':'View tasks'}</button></div>`;$('#chat-return').onclick=()=>{clearChat();navigate('earn')};$('#chat-another').onclick=()=>{clearChat();navigate(remaining?'earn':'tasks')}","$('#chat-ready').innerHTML=`<b>Guided chat completed</b><small>${credited?`${format(credited)} approved · `:''}${remaining} chat${remaining===1?'':'s'} remaining today.</small><p class=\"next-activity-label\">Choose your next activity</p><div class=\"chat-next-grid\"><button class=\"secondary\" data-chat-next=\"earn\">${remaining?'Another chat':'Earn hub'}</button><button class=\"secondary\" data-chat-next=\"tasks\">Tasks</button><button class=\"secondary\" data-chat-next=\"visits\">Sponsored visit</button><button class=\"secondary\" data-chat-next=\"referrals\">Share referral</button><button class=\"primary\" data-chat-next=\"home\">Return Home</button></div>`;$$('[data-chat-next]',$('#chat-ready')).forEach(button=>button.onclick=()=>{const route=button.dataset.chatNext;clearChat();navigate(route)})",'post-chat actions');
required("$('#chat-complete').disabled=true;$('#chat-complete').textContent='Verifying session…';","document.dispatchEvent(new CustomEvent('earnchat:chat-completion-requested'));$('#chat-complete').disabled=true;$('#chat-complete').textContent='Verifying session…';",'chat semantic event');
required("$('#task-open').onclick=async()=>{const popup=window.open('about:blank','_blank');","$('#task-open').onclick=async()=>{document.dispatchEvent(new CustomEvent('earnchat:task-opened',{detail:{taskId:task.id}}));const popup=window.open('about:blank','_blank');",'task semantic event');
required("if(!confirm(`Submit a ${format(amount)} ${wallet} withdrawal to ${accountName}?`))return;try{","if(!confirm(`Submit a ${format(amount)} ${wallet} withdrawal to ${accountName}?`))return;document.dispatchEvent(new CustomEvent('earnchat:withdrawal-requested',{detail:{wallet}}));try{",'withdraw semantic event');
required("$('#logout').onclick=async()=>{app.explicitLogout=true;try{await api.logout()}finally{clearChat();","$('#logout').onclick=async()=>{app.explicitLogout=true;try{await api.logout()}finally{clearChat();localStorage.removeItem(chatRecoveryKey());",'logout recovery cleanup');

for(const token of['About 2 minutes','minimum two minutes','two-minute session','120-elapsed',' / 02:00','<120)return','#public-stats','#public-total','#public-online']){
  if(app.includes(token))throw new Error(`Consolidated source still contains obsolete token: ${token}`);
}
for(const token of['CHAT_SECONDS=45','CHAT_RECOVERY_MS','CHAT_PROMPT_SETS',' / 00:45','data-chat-next','earnchat:chat-completion-requested']){
  if(!app.includes(token))throw new Error(`Consolidated source is missing contract: ${token}`);
}
fs.writeFileSync(path,app);
console.log('Earn Chat application source consolidated successfully.');
